{
 "title": "Batch Surveillance",
 "description": "I'm Batman",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Service State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aegis Stub Exporter State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=~\"aegis_stub_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aegis VTS Exporter State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"aegis_vts_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alfred",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"alfred\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coubertin",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"coubertin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cupidon",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"cupidon\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alfred DB",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{job=\"db_exporter_a\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Petrus DB",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{job=\"db_exporter_p\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hermes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"hermes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lovelace",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"lovelace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ludo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"ludo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mnemosine",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"mnemosine\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Petrus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"petrus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mnemosine DB",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{job=\"db_exporter_m\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 } }
 ]
}