# Generated by Django 5.0.3 on 2024-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashed_password', models.CharField(max_length=128)),
            ],
        ),
    ]
