# Generated by Django 5.0.3 on 2024-05-16 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hashed_password', models.CharField(max_length=128)),
                ('nick', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Nick must contain 3 to 16 characters, (uppercase, lowercase, digit or underscore)', regex='^[a-zA-Z0-9_]{3,16}$')])),
            ],
        ),
    ]
