curl -X GET --cacert config/certs/ca/ca.crt -u elastic:elastic123 "http://localhost:5601/api/kibana/dashboards/export?dashboard=45c31047-8d22-4496-88a1-187eaee249c7" -H 'kbn-xsrf: true'
{
  "version": "8.14.1",
  "objects": [
    {
      "id": "45c31047-8d22-4496-88a1-187eaee249c7",
      "type": "dashboard",
      "namespaces": [
        "default"
      ],
      "updated_at": "2024-06-13T15:52:49.582Z",
      "created_at": "2024-06-13T15:52:49.582Z",
      "created_by": "u_mGBROF_q5bmFCATbLXAcCwKa0k8JvONAwSruelyKA5E_0",
      "version": "WzUzLDFd",
      "attributes": {
        "version": 2,
        "kibanaSavedObjectMeta": {
          "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
        },
        "description": "",
        "refreshInterval": {
          "pause": true,
          "value": 60000
        },
        "timeRestore": true,
        "optionsJSON": "{\"useMargins\":true,\"syncColors\":false,\"syncCursor\":true,\"syncTooltips\":false,\"hidePanelTitles\":false}",
        "panelsJSON": "[{\"type\":\"visualization\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":19,\"i\":\"789bc009-06f7-4672-bd07-f60509544c34\"},\"panelIndex\":\"789bc009-06f7-4672-bd07-f60509544c34\",\"embeddableConfig\":{\"savedVis\":{\"id\":\"\",\"title\":\"\",\"description\":\"\",\"type\":\"markdown\",\"params\":{\"fontSize\":12,\"openLinksInNewTab\":false,\"markdown\":\"# Nginx Logs Dashboard\\n\\n## Overview\\n\\nWelcome to the Nginx Logs Dashboard. This dashboard provides a comprehensive view of the logs generated by our Nginx servers.\\n\\n## Why We Monitor Nginx Logs\\n\\n1. **Performance Monitoring**: Analyzing response times and request rates helps in identifying performance bottlenecks.\\n2. **Error Tracking**: Detecting 4xx and 5xx status codes early helps in troubleshooting client and server errors.\\n3. **Security Analysis**: Monitoring access patterns can reveal unauthorized access attempts and potential security threats.\\n4. **Traffic Insights**: Understanding traffic patterns assists in capacity planning and improving the user experience.\\n\\nRegularly reviewing Nginx logs ensures our web applications run smoothly, securely, and efficiently.\"},\"uiState\":{},\"data\":{\"aggs\":[],\"searchSource\":{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}}},\"enhancements\":{}}},{\"type\":\"lens\",\"gridData\":{\"x\":24,\"y\":0,\"w\":24,\"h\":7,\"i\":\"38ec2c7d-ae73-47e2-b19c-a8e4478815df\"},\"panelIndex\":\"38ec2c7d-ae73-47e2-b19c-a8e4478815df\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsMetric\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"nginx-data\",\"name\":\"indexpattern-datasource-layer-ce778804-d2f1-4a3d-91ed-e848dc179ae7\"}],\"state\":{\"visualization\":{\"layerId\":\"ce778804-d2f1-4a3d-91ed-e848dc179ae7\",\"layerType\":\"data\",\"metricAccessor\":\"8971e598-9a7f-4e81-a6ae-989cd968da19\",\"breakdownByAccessor\":\"0f24c3e0-32d2-4a21-8de6-95d8cb2670b6\",\"palette\":{\"type\":\"palette\",\"name\":\"status\",\"params\":{\"name\":\"status\",\"reverse\":false,\"rangeType\":\"percent\",\"rangeMin\":0,\"rangeMax\":100,\"progression\":\"fixed\",\"stops\":[{\"color\":\"#209280\",\"stop\":33.33},{\"color\":\"#d6bf57\",\"stop\":66.66},{\"color\":\"#cc5642\",\"stop\":100}],\"steps\":3,\"colorStops\":[],\"continuity\":\"all\",\"maxSteps\":5}},\"icon\":\"globe\",\"maxCols\":1,\"collapseFn\":\"max\"},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"formBased\":{\"layers\":{\"ce778804-d2f1-4a3d-91ed-e848dc179ae7\":{\"columns\":{\"0f24c3e0-32d2-4a21-8de6-95d8cb2670b6\":{\"label\":\"Top value of Client IP\",\"dataType\":\"ip\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"client_ip\",\"isBucketed\":true,\"params\":{\"size\":1,\"orderBy\":{\"type\":\"column\",\"columnId\":\"8971e598-9a7f-4e81-a6ae-989cd968da19\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"include\":[],\"exclude\":[],\"includeIsRegex\":false,\"excludeIsRegex\":false}},\"8971e598-9a7f-4e81-a6ae-989cd968da19\":{\"label\":\"Unique Visitors\",\"dataType\":\"number\",\"operationType\":\"unique_count\",\"scale\":\"ratio\",\"sourceField\":\"client_ip\",\"isBucketed\":false,\"params\":{\"emptyAsNull\":true},\"customLabel\":true}},\"columnOrder\":[\"0f24c3e0-32d2-4a21-8de6-95d8cb2670b6\",\"8971e598-9a7f-4e81-a6ae-989cd968da19\"],\"incompleteColumns\":{},\"sampling\":1}}},\"indexpattern\":{\"layers\":{}},\"textBased\":{\"layers\":{}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{}}}]",
        "timeFrom": "now-15m",
        "title": "Nginx-Dashboard",
        "timeTo": "now"
      },
      "references": [
        {
          "type": "index-pattern",
          "id": "nginx-data",
          "name": "38ec2c7d-ae73-47e2-b19c-a8e4478815df:indexpattern-datasource-layer-ce778804-d2f1-4a3d-91ed-e848dc179ae7"
        }
      ],
      "managed": false,
      "coreMigrationVersion": "8.8.0",
      "typeMigrationVersion": "10.2.0"
    },
    {
      "id": "nginx-data",
      "type": "index-pattern",
      "namespaces": [
        "default"
      ],
      "updated_at": "2024-06-13T15:47:18.970Z",
      "created_at": "2024-06-13T15:34:39.972Z",
      "version": "WzQ2LDFd",
      "attributes": {
        "fieldAttrs": "{\"client_ip\":{\"customLabel\":\"Client IP\"},\"method\":{\"customLabel\":\"Method\"},\"request\":{\"customLabel\":\"Request\"},\"response_size\":{\"customLabel\":\"Response Size\"},\"status_code\":{\"customLabel\":\"Status Code\"},\"timestamp\":{\"customLabel\":\"Timestamp\"},\"user_agent\":{\"customLabel\":\"User Agent\"}}",
        "title": "nginx-index-*",
        "sourceFilters": "[]",
        "fields": "[]",
        "fieldFormatMap": "{}",
        "runtimeFieldMap": "{}",
        "name": "My Nginx Data View",
        "allowHidden": false
      },
      "references": [],
      "managed": false,
      "coreMigrationVersion": "8.8.0",
      "typeMigrationVersion": "8.0.0"
    }
  ]
}