#version: '3.8'

networks:
  aegis guard: {}

  atlas:
    internal: true

  sentinel:
    internal: true

volumes:
  shared_code:
    driver: local
    driver_opts:
      type: none
      device: ./requirements/shared_code
      o: bind

  certificates:
    driver: local

  elastic_data:
    driver: local

  kibana_data:
    driver: local

  logstash_data:
    driver: local

services:
# Reverse proxy container
  aegis:
    depends_on:
      aether:
        condition: service_started
      apollo:
        condition: service_healthy
      iris:
        condition: service_started
      malevitch:
        condition: service_started
      orion:
        condition: service_started
    container_name: aegis
    image: aegis
    build:
      context: ./requirements/aegis
      dockerfile: Dockerfile
      args:
        PROXY_CONF: $PROXY_CONF
    env_file: .env
    ports:
      # - "80:80"
      # - "443:443"
      - "7999:80"
      - "8000:443"
    volumes:
      - ./requirements/aegis:/usr/share/nginx/html
      - /etc/letsencrypt/archive/batch42.me:/etc/letsencrypt/live/batch42.me:r
    networks:
      - aegis guard
      - atlas
      - sentinel
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:8000 | echo -e 'cannot curl'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

# Logstash container
  aether:
    depends_on:
      apollo:
        condition: service_healthy
      iris:
        condition: service_started
    container_name: aether
    image: docker.elastic.co/logstash/logstash:8.12.2
    labels:
      co.elastic.logs/module: logstash
    user: root
    volumes:
      - certificates:/usr/share/logstash/certs
      - logstash_data:/usr/share/logstash/data
      - ./requirements/aether/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - "NODE_NAME=logstash"
      - "XPACK_MONITORING_ENABLED=false"
      - "ELASTIC_USER=${ELASTIC_USER}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "ELASTIC_HOSTS=https://apollo:9200"
      - "HTTP_HOST: '0.0.0.0'"
      - "XPACK_MONITORING_ELASTICSEARCH_HOSTS: [ 'http://apollo:9200' ]"
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    networks:
      - sentinel
    restart: on-failure
    # ports:
    #   - "5044:5044/udp"

# Elastisearch container
  apollo:
    depends_on:
      setup:
        condition: service_healthy
    container_name: apollo
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - certificates:/usr/share/elasticsearch/config/certs:ro
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - sentinel
    environment:
      - "discovery.type=single-node"
      - "cluster.name=${CLUSTER_NAME}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "network.host=0.0.0.0"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.security.http.ssl.key=certs/apollo/apollo.key"
      - "xpack.security.http.ssl.certificate=certs/apollo/apollo.crt"
      - "xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.transport.ssl.key=certs/apollo/apollo.key"
      - "xpack.security.transport.ssl.certificate=certs/apollo/apollo.crt"
      - "xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "xpack.license.self_generated.type=${LICENSE}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

# Kibana container
  iris:
    depends_on:
      apollo:
        condition: service_healthy
    container_name: iris
    image: docker.elastic.co/kibana/kibana:8.12.2
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - ./requirements/aegis:/usr/share/nginx/html
      - certificates:/usr/share/kibana/config/certs
      - kibana_data:/usr/share/kibana/data
      - ./tokens:/vault
    networks:
      - sentinel
    environment:
      - "SERVERNAME=https://localhost:8000/iris/"
      - "ELASTICSEARCH_HOSTS=https://apollo:9200"
      - "ELASTICSEARCH_USERNAME=kibana_system"
      - "ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt"
      - "SERVER_SSL_ENABLED=false"
      - "XPACK_REPORTING_ROLES_ENABLED=false"
      - "XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPT_KEY}"
      - "XPACK_REPORTING_ENCRYPTIONKEY=${REP_ENCRYPT_KEY}"
      - "XPACK_SECURITY_ENCRYPTIONKEY=${SEC_ENCRYPT_KEY}"
      - "SERVER_REWRITEBASEPATH=true"
      - "SERVER_BASEPATH=/iris"
      - "SERVER_PUBLICBASEURL=https://localhost:8000/iris"
    # healthcheck:
    #  test:
    #    [
    #      "CMD-SHELL",
    #      "curl -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
    #    ]
    #  interval: 10s
    #  timeout: 10s
    #  retries: 120

# Front container
  malevitch:
    container_name: malevitch
    image: malevitch
    build:
      context: ./requirements/malevitch
      dockerfile: Dockerfile
    volumes:
      - ./requirements/malevitch:/usr/share/nginx/html
    ports:
      - "8007:80"
    networks:
      - atlas
    restart: on-failure

# Filebeat container
  orion:
    container_name: orion
    image: orion
    labels:
      co.elastic.logs/module: filebeat
    build:
      context: ./requirements/orion/
      dockerfile: Dockerfile
    volumes:
      - ./requirements/orion/conf/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
    user: "root"
    environment:
      - "ELASTIC_USER=${ELASTIC_USER}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "ELASTIC_HOSTS=https://apollo:9200"
    networks:
      - sentinel

# ELK setup container
  setup:
    container_name: setup
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "KIBANA_PASSWORD=${KIBANA_PASSWORD}"
    build:
      context: ./requirements/setup
      dockerfile: Dockerfile
    volumes:
      - certificates:/usr/share/elasticsearch/config/certs
    user: "0"
    command: ./tools/setup.sh
    networks:
      - sentinel
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/apollo/apollo.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
