services:
# # Profil container
  alfred:
    # depends_on:
    #   alfred_db:
    #     condition: service_healthy
    #   aether:
    #     condition: service_healthy
    container_name: alfred
    build:
      context: alfred
      dockerfile: Dockerfile
    volumes:
      - alfred/alfred_project:/app
      - ./tokens/alfred:/app/tokens
      - shared_code:/app/shared
    ports:
      - "8001:8001"
    networks:
      - atlas
      - alfred_network
    restart: on-failure

# # Authentification container
  petrus:
    depends_on:
      # petrus_db:
      #   condition: service_healthy
      # aether:
      #   condition: service_healthy
    container_name: petrus
    build:
      context: petrus
      dockerfile: Dockerfile
    volumes:
      - petrus/petrus_project:/app
      - shared_code:/app/shared
      - ./tokens/petrus:/app/tokens
    ports:
      - "8009:8009"
    networks:
      - atlas
      - petrus_network
    restart: on-failure