# Generated by Django 5.0.1 on 2024-04-30 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Nick must contain 3 to 16 characters, (uppercase, lowercase, digit or underscore)', regex='^[a-zA-Z0-9_]{3,16}$')])),
                ('email', models.EmailField(max_length=254)),
                ('font', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('lang', models.IntegerField(choices=[(1, 'fr'), (2, 'eng'), (3, 'zh')], default=1)),
                ('friends', models.ManyToManyField(blank=True, to='user_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receive', to='user_management.client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sended', to='user_management.client')),
            ],
        ),
    ]
