# Generated by Django 5.0.1 on 2024-05-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lang',
            field=models.IntegerField(choices=[(1, 'fr'), (2, 'en'), (3, 'zh')], default=1),
        ),
    ]
