#---- base image ------------------------------------------------------#

FROM    docker.elastic.co/beats/filebeat:8.13.2

#---- config ----------------------------------------------------------#

COPY    conf/filebeat.yml /usr/share/filebeat/filebeat.yml