"""
Django settings for mnemosine_project project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from shared.settings import SHARED_MIDDLEWARE as shared_middleware, add_prometheused_middleware, LOGGING
from shared.settings import add_prometheused_apps
from pathlib import Path
from shared.jwt_management import get_ressource_from_vault
try:
    from tokens.token import vault_token
except ModuleNotFoundError:
    print("Warn vault_token not found")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vk+-gf01(vmkl+@oco5=9+pcno8i5=1wg!6+9@l_&*u!m)fv5#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

PROJECT_APPS = [
    'memory',
]

INSTALLED_APPS = add_prometheused_apps(PROJECT_APPS)

PROJECT_OWN_MIDDLEWARE = [
]

MIDDLEWARE = add_prometheused_middleware(shared_middleware + PROJECT_OWN_MIDDLEWARE)

ROOT_URLCONF = 'mnemosine_project.urls'

WSGI_APPLICATION = 'mnemosine_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_ressource_from_vault(vault_token, 'mnemosine/mnemosine_db', 'db'),
        'USER': get_ressource_from_vault(vault_token, 'mnemosine/mnemosine_user', 'user'),
        'PASSWORD': get_ressource_from_vault(vault_token, 'mnemosine/mnemosine_password', 'password'),
        'HOST': 'mnemosine_db',
        'PORT': '5432',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
