filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log

filebeat.autodiscover:
  providers:
   - type: docker
     hints.enabled: true
     hints.default_config:
        type: container
        paths:
          - /var/log/containers/*-${data.container.id}.log


processors:
- add_docker_metadata: ~


setup.kibana:
 host: ["iris:5601"]
 username: "elastic"
 password: "elastic123"

output/logstash:
  hosts: ["aether:5044"]

# output.elasticsearch:
#  hosts: ${ELASTIC_HOSTS}
#  username: ${ELASTIC_USER}
#  password: ${ELASTIC_PASSWORD}
#  ssl.enabled: true
#  ssl.certificate_authorities: "config/certs/ca/ca.crt"
