filebeat.inputs:
  - type: docker
    containers.ids: '*'
    processors:
      - add_docker_metadata: ~

# output.elasticsearch:
# hosts: ["https://apollo:9200"]
# username: "${ELASTIC_USER}"
# password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "iris:5601" 
  username: "kibana_system"
  password: "kibana123"

output.elasticsearch:
  hosts: ["https://apollo:9200"]
  username: "orion"
  password: "elastic123" 
  ssl:
    enabled: true
    ca_trusted_fingerprint: "b9a10bbe64ee9826abeda6546fc988c8bf798b41957c33d05db736716513dc9c" 