# Sample config for Prometheus.

global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'Alertmanager'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - alert.rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['mensura:8011']

  - job_name: 'mensura_exporter'
    static_configs:
      - targets: ['mensura_exporter:9100']

  - job_name: 'db_exporter_a'
    static_configs:
      - targets: ['db_exporter_a:9187']

  - job_name: 'db_exporter_m'
    static_configs:
      - targets: ['db_exporter_m:9187']

  - job_name: 'db_exporter_p'
    static_configs:
      - targets: ['db_exporter_p:9187']

  - job_name: 'aegis_vts_exporter'
    scrape_interval:     30s
    static_configs:
      - targets: ['aegis_vts_exporter:9913']

  - job_name: 'aegis_stub_exporter'
    scrape_interval:     30s
    static_configs:
      - targets: ['aegis_stub_exporter:9113']

  - job_name: 'alfred'
    metrics_path: /metrics/metrics
    scrape_interval:     30s
    static_configs:
      - targets: ['alfred:8001']

  - job_name: 'coubertin'
    metrics_path: /metrics/metrics
    scrape_interval:     30s
    static_configs:
      - targets: ['coubertin:8002']

  - job_name: 'cupidon'
    metrics_path: /metrics/metrics
    scrape_interval:     30s
    static_configs:
      - targets: ['cupidon:8003']

  - job_name: 'hermes'
    metrics_path: /metrics/metrics
    scrape_interval:     30s
    static_configs:
      - targets: ['hermes:8004']

  - job_name: 'lovelace'
    metrics_path: /metrics/metrics
    scrape_interval:     30s
    static_configs:
      - targets: ['lovelace:8005']

  - job_name: 'ludo'
    metrics_path: /metrics/metrics
    scrape_interval:     30s
    static_configs:
      - targets: ['ludo:8006']

  - job_name: 'mnemosine'
    metrics_path: /metrics/metrics
    scrape_interval:     30s
    static_configs:
      - targets: ['mnemosine:8008']

  - job_name: 'petrus'
    metrics_path: /metrics/metrics
    scrape_interval:     30s
    static_configs:
      - targets: ['petrus:8009']
