#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER $MNEMOSINE_USER WITH PASSWORD '$MNEMOSINE_PASSWORD';
CREATE DATABASE $MNEMOSINE_DB;
GRANT ALL PRIVILEGES ON DATABASE $MNEMOSINE_DB TO $MNEMOSINE_USER;
EOSQL
