name: Build Docker Containers

on:
  #push:
  #  branches:
  #    - TRA-237-Compile-ModSecurity-Quick-CI-Job-Health-Test
  pull_request:
    branches:
      - dev
# jobs:
 # build:
 /*   runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file for CI
      run: |
          touch .env
          echo  >> .env "ELASTIC_USER=elastic
          ELASTIC_PASSWORD=test
          STACK_VERSION=8.12.2
          CLUSTER_NAME=docker-cluste
          LICENSE=basic
          ES_PORT=9200
          KIBANA_PORT=5601
          KIBANA_PASSWORD=test
          GRAFANA_PASSWD=grafana
          PROXY_CONF=proxy.conf
          CI=ci"
          mkdir requirements/aegis/Modsecurity

    - name: Build containers
      run: |
          make build
          */

    #- name: Health Check Mensura
    #  run: curl -Lk https://localhost:8000/mensura/

    #- name: Health Check Davinci
    #  run: |
    #        curl -k -X GET https://localhost:8000/davinci/api/health
    #        grep '"database": "ok"'
