name: Discord Notifications

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Discord Notification
      uses: n0mad3v/discord-webhook@v1.0.0
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        username: GitHub Action
        message: A new pull request has been merged to the dev branch!