name: Django tests launching

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Create virtual environement
      run: |
          make copyfile
          echo  >> .env "ELASTIC_USER=elastic
          ELASTIC_PASSWORD=test
          STACK_VERSION=8.12.2
          CLUSTER_NAME=docker-cluste
          LICENSE=basic
          ES_PORT=9200
          KIBANA_PORT=5601
          KIBANA_PASSWORD=test
          GRAFANA_PASSWD=grafana
          PROXY_CONF=proxy.conf
          CI=ci"
          python3 -m venv ci_env
          source ci_env/bin/activate
          pip install -r global_requirements.txt
          make test

